---
- name: delete existing ec2 instance(s)
  ec2_instance:
    state: absent
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ ec2_region }}'
    instance_type: '{{ item.type|default(ec2_instance_type) }}'
    security_group: '{{ item.security_group|default(ec2_security_group) }}'
    key_name: '{{ ec2_key_name }}'
    image_id: '{{ item.id }}'
    wait: '{{ terminate_ec2_wait_upon_termination | default(true) | bool }}'
    wait_timeout: '600'
    filters:
      'tag:Name': '{{ec2_name_prefix}}-{{item.name}}'
      'tag:ANSIBLE_INSTALL_METHOD': '{{ansible_install_method|default("nightly")}}'
  with_items: '{{ ec2_images }}'
