---
# Download ansible-tower-setup and run the setup playbook

- name: Update systemd
  yum:
    name: systemd*
    state: latest
    update_cache: true
    update_only: true

- name: remove any previously extracted tarball files
  file:
    path: '/tmp/setup'
    state: absent

- name: untar ansible-tower-setup
  unarchive:
    src: '{{aw_repo_url}}/{{awx_setup_path}}'
    dest: '/tmp/'
    remote_src: true
    extra_opts:
      - --transform
      - s|^[^/]*|setup|

- name: is awx already installed?
  stat:
    path: /etc/tower/tower.cert
  register: is_awx_installed

- name: create sudoers config
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/tower-qa
    mode: '0640'
    owner: 'root'
    group: 'root'

- name: create inventory file
  template:
    src: inventory.j2
    dest: /tmp/setup/inventory
  when: not cluster_install | default(false) | bool

- name: create cluster inventory file
  template:
    src: inventory_cluster.j2
    dest: /tmp/setup/inventory
  when: cluster_install | default(false) | bool

- name: create vars.yml file
  template:
    src: vars.yml.j2
    dest: /tmp/setup/vars.yml

- name: create vars-static.yml file
  copy:
    src: vars-static.yml
    dest: /tmp/setup/vars-static.yml

- name: setup.sh
  # Also set AW_REPO_URL so during bootstrap phase we use correct dependencies repo
  command: ./setup.sh -e @vars.yml -e @vars-static.yml
  args:
    chdir: /tmp/setup
  environment:
    # To install with ansible < 1.9, sudo support is accessible by way of the following variable
    # ANSIBLE_SUDO: 'True'
    ANSIBLE_BECOME: 'True'
    AW_REPO_URL: '{{ aw_repo_url }}'
    ANSIBLE_BECOME_METHOD: 'sudo'
    ANSIBLE_HOST_KEY_CHECKING: 'False'

- name: verify Tower API is accepting connections
  uri:
    url: "{{'http' if disable_ssl else 'https'}}://localhost/api/v2/config/"
    validate_certs: false
    user: 'admin'
    password: '{{ admin_password }}'
    force_basic_auth: true
  register: result
  until: result['status']|default(0) == 200
  retries: 6
  delay: 10

- name: verify memcached is up and running
  block:
    - name: install ncat
      package:
        name: nmap-ncat
        state: installed

    - name: check memcached uptime stat
      shell: "echo stats | nc -U /var/run/memcached/memcached.sock | grep uptime"
